/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package wordgame;
import java.util.*;
/**
 *
 * @author rkaune
 */
public class WordGameFrame extends javax.swing.JFrame {
    ArrayList <String> names = new ArrayList();
    ArrayList <String> verbs = new ArrayList();
    ArrayList <String> adverbs = new ArrayList();
    ArrayList <String> nouns = new ArrayList();
    ArrayList <String> adjectives = new ArrayList();

    Random rn = new Random();
    /**
     * Creates new form WordGameFrame
     */
    public WordGameFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        displayButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputBox = new javax.swing.JTextArea();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        initButton = new javax.swing.JButton();
        nameInput = new javax.swing.JTextField();
        verbInput = new javax.swing.JTextField();
        adverbInput = new javax.swing.JTextField();
        nounInput = new javax.swing.JTextField();
        adjectiveInput = new javax.swing.JTextField();
        addButtonName = new javax.swing.JButton();
        removeButtonName = new javax.swing.JButton();
        addButtonVerb = new javax.swing.JButton();
        removeButtonVerb = new javax.swing.JButton();
        addButtonAdverb = new javax.swing.JButton();
        removeButtonAdverb = new javax.swing.JButton();
        addButtonNoun = new javax.swing.JButton();
        removeButtonNoun = new javax.swing.JButton();
        addButtonAdjective = new javax.swing.JButton();
        removeButtonAdjective = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("The Word Game");

        jLabel2.setText("Enter a Name");

        jLabel3.setText("Enter a verb");

        jLabel4.setText("Enter an adverb");

        jLabel5.setText("Enter a noun");

        jLabel6.setText("Enter an adjective");

        displayButton.setText("Display Message");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBar(null);

        outputBox.setEditable(false);
        outputBox.setColumns(20);
        outputBox.setLineWrap(true);
        outputBox.setRows(5);
        outputBox.setWrapStyleWord(true);
        jScrollPane1.setViewportView(outputBox);

        addButton.setText("Add Words");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove Words");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        initButton.setText("Initialize");
        initButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initButtonActionPerformed(evt);
            }
        });

        verbInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verbInputActionPerformed(evt);
            }
        });

        addButtonName.setText("Add");
        addButtonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonNameActionPerformed(evt);
            }
        });

        removeButtonName.setText("Remove");
        removeButtonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonNameActionPerformed(evt);
            }
        });

        addButtonVerb.setText("Add");
        addButtonVerb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonVerbActionPerformed(evt);
            }
        });

        removeButtonVerb.setText("Remove");
        removeButtonVerb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonVerbActionPerformed(evt);
            }
        });

        addButtonAdverb.setText("Add");
        addButtonAdverb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonAdverbActionPerformed(evt);
            }
        });

        removeButtonAdverb.setText("Remove");
        removeButtonAdverb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonAdverbActionPerformed(evt);
            }
        });

        addButtonNoun.setText("Add");
        addButtonNoun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonNounActionPerformed(evt);
            }
        });

        removeButtonNoun.setText("Remove");
        removeButtonNoun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonNounActionPerformed(evt);
            }
        });

        addButtonAdjective.setText("Add");
        addButtonAdjective.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonAdjectiveActionPerformed(evt);
            }
        });

        removeButtonAdjective.setText("Remove");
        removeButtonAdjective.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonAdjectiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adjectiveInput)
                                    .addComponent(nounInput)
                                    .addComponent(adverbInput)
                                    .addComponent(verbInput)
                                    .addComponent(nameInput)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addButtonName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeButtonName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addButtonVerb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeButtonVerb))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addButtonAdverb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeButtonAdverb))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addButtonNoun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeButtonNoun))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addButtonAdjective)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeButtonAdjective, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(displayButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(initButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButtonName)
                    .addComponent(removeButtonName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verbInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(addButtonVerb)
                    .addComponent(removeButtonVerb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(adverbInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addButtonAdverb)
                        .addComponent(removeButtonAdverb)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nounInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addButtonNoun)
                        .addComponent(removeButtonNoun)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(adjectiveInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addButtonAdjective)
                        .addComponent(removeButtonAdjective)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayButton)
                    .addComponent(addButton)
                    .addComponent(removeButton)
                    .addComponent(initButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initButtonActionPerformed
        Collections.addAll(names, "Rudolph", "Santa");
        Collections.addAll(verbs, "flew", "crashed");
        Collections.addAll(adverbs, "quickly", "slowly");
        Collections.addAll(nouns, "mountain", "snowman");
        Collections.addAll(adjectives, "huge", "abominable");
        initButton.setEnabled(false);
    }//GEN-LAST:event_initButtonActionPerformed

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        outputBox.setText( names.get(rn.nextInt(names.size()))
      + " " + adverbs.get(rn.nextInt(adverbs.size()))
      + " " + verbs.get(rn.nextInt(verbs.size()))
      + " on top of the "  + adjectives.get(rn.nextInt(adjectives.size()))
      + " " + nouns.get(rn.nextInt(nouns.size()))
      + " trying to escape the " + adjectives.get(rn.nextInt(adjectives.size()))
      + " " + nouns.get(rn.nextInt(nouns.size())) + "!");
    }//GEN-LAST:event_displayButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        names.add(nameInput.getText());
        verbs.add(verbInput.getText());
        adverbs.add(adverbInput.getText());
        nouns.add(nounInput.getText());
        adjectives.add(adjectiveInput.getText());
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // Remove the last element from the end of each of the Arrays.
        names.remove(names.size()-1);
        verbs.remove(verbs.size()-1);
        adverbs.remove(adverbs.size()-1);
        nouns.remove(nouns.size()-1);
        adjectives.remove(adjectives.size()-1);

        // These trace statements have been added to testing purposes.
        System.out.println("Names: " + names);
        System.out.println("Verbs: " + verbs);
        System.out.println("Adverbs: " + adverbs);
        System.out.println("Nouns: " + nouns);
        System.out.println("Adjectives: " + adjectives);
        System.out.println("\n");
    }//GEN-LAST:event_removeButtonActionPerformed

    private void verbInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verbInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verbInputActionPerformed

    private void addButtonAdverbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonAdverbActionPerformed
        adverbs.add(adverbInput.getText());
    }//GEN-LAST:event_addButtonAdverbActionPerformed

    private void addButtonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonNameActionPerformed
        names.add(nameInput.getText());
    }//GEN-LAST:event_addButtonNameActionPerformed

    private void addButtonVerbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonVerbActionPerformed
        verbs.add(verbInput.getText());
    }//GEN-LAST:event_addButtonVerbActionPerformed

    private void addButtonNounActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonNounActionPerformed
        nouns.add(nounInput.getText());
    }//GEN-LAST:event_addButtonNounActionPerformed

    private void addButtonAdjectiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonAdjectiveActionPerformed
         names.add(adjectiveInput.getText());
    }//GEN-LAST:event_addButtonAdjectiveActionPerformed

    private void removeButtonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonNameActionPerformed
        names.remove(nameInput.getText());
    }//GEN-LAST:event_removeButtonNameActionPerformed

    private void removeButtonVerbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonVerbActionPerformed
        verbs.remove(verbInput.getText());
    }//GEN-LAST:event_removeButtonVerbActionPerformed

    private void removeButtonAdverbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonAdverbActionPerformed
       adverbs.remove(adverbInput.getText());
    }//GEN-LAST:event_removeButtonAdverbActionPerformed

    private void removeButtonNounActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonNounActionPerformed
       nouns.remove(nounInput.getText());
    }//GEN-LAST:event_removeButtonNounActionPerformed

    private void removeButtonAdjectiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonAdjectiveActionPerformed
       adjectives.remove(adjectiveInput.getText());
    }//GEN-LAST:event_removeButtonAdjectiveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordGameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButtonAdjective;
    private javax.swing.JButton addButtonAdverb;
    private javax.swing.JButton addButtonName;
    private javax.swing.JButton addButtonNoun;
    private javax.swing.JButton addButtonVerb;
    private javax.swing.JTextField adjectiveInput;
    private javax.swing.JTextField adverbInput;
    private javax.swing.JButton displayButton;
    private javax.swing.JButton initButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField nounInput;
    private javax.swing.JTextArea outputBox;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton removeButtonAdjective;
    private javax.swing.JButton removeButtonAdverb;
    private javax.swing.JButton removeButtonName;
    private javax.swing.JButton removeButtonNoun;
    private javax.swing.JButton removeButtonVerb;
    private javax.swing.JTextField verbInput;
    // End of variables declaration//GEN-END:variables
}
